FROM node:22-slim AS build
ARG PORT=3000
ADD . /app
WORKDIR  /app
RUN corepack enable
RUN pnpm build

FROM build
ENV PORT=$PORT
COPY --from=build /app/.output /app/.output
CMD node .output/server/index.mjs